"""message

Revision ID: 3bca6e45b56f
Revises: 8cc1131fbf28
Create Date: 2025-05-27 14:26:48.002221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bca6e45b56f'
down_revision: Union[str, None] = '8cc1131fbf28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('drivers', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('drivers', sa.Column('gender', sa.Text(), nullable=True))
    op.add_column('drivers', sa.Column('id_number', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'vehicle_id')
    op.drop_column('drivers', 'id_number')
    op.drop_column('drivers', 'gender')
    op.drop_column('drivers', 'email')
    op.drop_column('drivers', 'name')
    # ### end Alembic commands ###
