"""changes

Revision ID: 478b81519414
Revises: 83c9b76d9399
Create Date: 2025-05-28 11:19:58.734686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478b81519414'
down_revision: Union[str, None] = '83c9b76d9399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'image')
    # ### end Alembic commands ###
