"""message

Revision ID: 6b95305ef16d
Revises: 79106b7a38ad
Create Date: 2025-06-03 21:28:43.750886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b95305ef16d'
down_revision: Union[str, None] = '79106b7a38ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passangers', sa.Column('No_plate', sa.Text(), nullable=True))
    op.add_column('passangers', sa.Column('vehicle_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passangers', 'vehicle_type')
    op.drop_column('passangers', 'No_plate')
    # ### end Alembic commands ###
