"""driver

Revision ID: 73f2bc9c9800
Revises: 3bca6e45b56f
Create Date: 2025-05-27 19:55:02.669074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f2bc9c9800'
down_revision: Union[str, None] = '3bca6e45b56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'created_at')
    # ### end Alembic commands ###
