"""message

Revision ID: 982547cd7577
Revises: c0daca1b57cd
Create Date: 2025-06-03 13:19:22.343524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982547cd7577'
down_revision: Union[str, None] = 'c0daca1b57cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_type', sa.Text(), nullable=True))
    op.drop_column('vehicles', 'route_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('route_id', sa.TEXT(), nullable=True))
    op.drop_column('vehicles', 'vehicle_type')
    # ### end Alembic commands ###
