"""message

Revision ID: a2b20ba3b793
Revises: 478b81519414
Create Date: 2025-05-30 13:35:01.857461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b20ba3b793'
down_revision: Union[str, None] = '478b81519414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('image', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
