"""message

Revision ID: c0daca1b57cd
Revises: cd154c20a645
Create Date: 2025-06-02 22:35:13.974200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0daca1b57cd'
down_revision: Union[str, None] = 'cd154c20a645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('vehicle_type', sa.Text(), nullable=True))
    op.drop_column('drivers', 'vehicle_id')
    op.drop_column('drivers', 'id_number')
    op.drop_column('drivers', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('gender', sa.TEXT(), nullable=True))
    op.add_column('drivers', sa.Column('id_number', sa.INTEGER(), nullable=True))
    op.add_column('drivers', sa.Column('vehicle_id', sa.INTEGER(), nullable=True))
    op.drop_column('drivers', 'vehicle_type')
    # ### end Alembic commands ###
